// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FontSizer
{
    internal sealed partial class Vsix
    {
        public const string Id = "7071cd60-3d6d-4e90-81b9-513a334fab4c";
        public const string Name = "Font Sizer (Uwe Custom)";
        public const string Description = @"An easy way to change the editor and Visual Studio environment font sizes, now with configurable environment step size.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Uwe Keim";
        public const string Tags = "font, presentation, zoom, customization";
    }
}